### ISSUE TITLE
Using the context menu on Touch devices

### ISSUE THREAD

**Issue by AjitPS** [cytoscape/cytoscape.js-cxtmenu#17] opened 2015-03-11 10:48 UTC
Hi,
I am using the circular context menu in my cytoscapeJS code. However, on tablets, it is not allowing me to hold to get the menu to appear and then click a menu item using multi-finger gestures. Is there code for touch gestures in the <b>cxtmenu</b> that can be modified to enable this ?
Or do I have to modify my cytoscapeJS code to allow for this ?

**Comment by maxkfranz** [comment] 2015-03-17 17:16
Duplicate of #16

**Closed by maxkfranz** 2015-03-17 17:16 UTC
Labels: duplicate
