### ISSUE TITLE
Tap-Hold to call cxtmenu doesn't work (Win8.1 / Android 4.4)

### ISSUE THREAD

**Issue by Braintelligence** [cytoscape/cytoscape.js-cxtmenu#16] opened 2015-03-08 02:08 UTC
Hi,
I'm using cxtmenu and it works with right click in windows but doesn't work with touch-tap&hold in Windows or Android.

Any ideas?

**Comment by Braintelligence** [comment] 2015-03-08 02:14
If I use an event listener like this:

cy.on('tap', 'node', function(){

would I overload the tapstart and tapend functions of the cxtmenu plugin, rendering them useless?

**Comment by Braintelligence** [comment] 2015-03-08 02:16
Commenting out the only other event listener I had (namely the one mentioned above) didn't help. Tap&Hold still doesn't work on Windows or Android.

**Comment by maxkfranz** [comment] 2015-03-17 17:15
It's always been a two finger context swipe.  Otherwise, you would conflict with drag.

**Comment by maxkfranz** [comment] 2015-03-17 17:16
Duplicate of #2, after looking some more

**Closed by maxkfranz** 2015-03-17 17:16 UTC
Labels: duplicate

**Comment by Braintelligence** [comment] 2015-03-19 12:33
The conflict with drag makes sense. I didn't know about the two-finger context swipe, though. Is that mentioned anywhere within cytoscape.js or the plugin?

**Comment by maxkfranz** [comment] 2015-03-19 16:08
Both

**Comment by Braintelligence** [comment] 2015-03-19 16:30
I guess you are referring to cxttap et al? They are mentioned on js.cytoscape.org indeed.
I didn't associate the word "swipes" in the README of the cxtmenu plugin with a "two-finger context swipe", though, so I missed this point.
Thanks for clearing it up.

**Comment by AjitPS** [comment] 2015-05-20 16:00
On a touch device, holding (taphold) with one finger allows me to drag the nodes around. However, if I continue holding a node, the radial context menu pops up (for a very short duration). Is there a way to ensure that the context menu stays visible instead of disappearing almost immediately ?

**Comment by maxkfranz** [comment] 2015-05-21 18:22
@AjitPS I can't reproduce this.  Are you using the latest version?  The menu opens on taphold for me -- i.e. only if I don't drag.

**Comment by AjitPS** [comment] 2015-06-11 14:58
@maxkfranz If I ````tap```` and or tap and hold (````taphold````) a node, I can drag it around.
Holding a node for a longer duration, shows the <i>context menu</i> (for a very brief duration). However, for some reason, it does not appear every time.
I want to allow users to drag by using ````taphold```` and drag and display the context menu if they do not drag, like you mentioned above.
